// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3uTGHRZYxMRop0ShJdjnSwgAnHAaGvN4',
    appId: '1:22010132142:web:360d8d5c30d31f470ddf3f',
    messagingSenderId: '22010132142',
    projectId: 'mitco-task',
    authDomain: 'mitco-task.firebaseapp.com',
    storageBucket: 'mitco-task.firebasestorage.app',
    measurementId: 'G-5QS61PENPD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfaeHPVbiGjpTAYzgqoMhuaZlwteSSrwA',
    appId: '1:22010132142:android:f1a246135ec94c7b0ddf3f',
    messagingSenderId: '22010132142',
    projectId: 'mitco-task',
    storageBucket: 'mitco-task.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDsk2qv0_SYW0yOat50bgKRW5agAOXR-hk',
    appId: '1:22010132142:ios:49417e21df6e9e3b0ddf3f',
    messagingSenderId: '22010132142',
    projectId: 'mitco-task',
    storageBucket: 'mitco-task.firebasestorage.app',
    iosBundleId: 'com.example.vactonline',
  );
}
